# Generated by Django 3.2.9 on 2021-11-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='partnerWarehouseId',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
