# Generated by Django 3.2.9 on 2021-11-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketPromoId', models.CharField(max_length=255)),
                ('subsidy', models.FloatField()),
                ('type', models.CharField(choices=[('MARKET_COUPON', 'MARKET_COUPON'), ('MARKET_DEAL', 'MARKET_DEAL'), ('MARKET_COIN', 'MARKET_COIN')], default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('shipmentDate', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='taxSystem',
            field=models.CharField(choices=[('ECHN', 'ECHN'), ('ENVD', 'ENVD'), ('OSN', 'OSN'), ('PSN', 'PSN'), ('USN', 'USN'), ('USN_MINUS_COST', 'USN_MINUS_COST')], default=None, max_length=200),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('CITY', 'CITY'), ('CITY_DISTRICT', 'CITY_DISTRICT'), ('CONTINENT', 'CONTINENT'), ('COUNTRY', 'COUNTRY'), ('COUNTRY_DISTRICT', 'COUNTRY_DISTRICT'), ('METRO_STATION', 'METRO_STATION'), ('MONORAIL_STATION', 'MONORAIL_STATION'), ('OTHERS_UNIVERSAL', 'OTHERS_UNIVERSAL'), ('OVERSEAS_TERRITORY', 'OVERSEAS_TERRITORY'), ('REGION', 'REGION'), ('SECONDARY_DISTRICT', 'SECONDARY_DISTRICT'), ('SETTLEMENT', 'SETTLEMENT'), ('SUBJECT_FEDERATION', 'SUBJECT_FEDERATION'), ('SUBJECT_FEDERATION_DISTRICT', 'SUBJECT_FEDERATION_DISTRICT'), ('SUBURB', 'SUBURB'), ('VILLAGE', 'VILLAGE')], max_length=200, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='graph.region')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('feedId', models.PositiveBigIntegerField()),
                ('offerId', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('buyerPrice', models.FloatField()),
                ('subsidy', models.FloatField()),
                ('count', models.IntegerField()),
                ('delivery', models.BooleanField()),
                ('params', models.CharField(max_length=255)),
                ('vat', models.CharField(choices=[('NO_VAT', 'NO_VAT'), ('VAT_0', 'VAT_0'), ('VAT_10', 'VAT_10'), ('VAT_10_110', 'VAT_10_110'), ('VAT_18', 'VAT_18'), ('VAT_18_118', 'VAT_18_118'), ('VAT_20', 'VAT_20'), ('VAT_20_120', 'VAT_20_120')], default=None, max_length=255)),
                ('fulfilmentShopId', models.PositiveBigIntegerField()),
                ('sku', models.CharField(max_length=255)),
                ('shopSku', models.CharField(max_length=255)),
                ('warehouseId', models.PositiveBigIntegerField()),
                ('promos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.promo')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('deliveryPartnerType', models.CharField(choices=[('YANDEX_MARKET', 'YANDEX_MARKET')], default='YANDEX_MARKET', max_length=100)),
                ('deliveryServiceId', models.PositiveBigIntegerField()),
                ('serviceName', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('DELIVERY', 'DELIVERY'), ('PICKUP', 'PICKUP'), ('POST', 'POST')], default=None, max_length=255, null=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graph.region')),
                ('shipments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='graph.delivery'),
            preserve_default=False,
        ),
    ]
