# Generated by Django 3.2.9 on 2021-11-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_item_offername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='offerName',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
