# Generated by Django 3.2.9 on 2021-11-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20211115_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='region',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='shipments',
        ),
        migrations.RemoveField(
            model_name='item',
            name='promos',
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='graph.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='graph.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='delivery',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='graph.delivery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='graph.delivery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='graph.order'),
        ),
    ]
