# Generated by Django 3.2.9 on 2021-11-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_auto_20211115_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='id',
            new_name='region_id',
        ),
    ]
