# Generated by Django 3.2.9 on 2021-11-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_rename_delivery_deliverymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverymodel',
            old_name='type',
            new_name='t_attention',
        ),
    ]
