# Generated by Django 3.2.9 on 2021-11-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0006_rename_id_delivery_region_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='deliveryServiceId',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='serviceName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
