# Generated by Django 3.2.9 on 2021-11-16 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_rename_type_region_regiont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymodel',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='graph.deliverymodel'),
            preserve_default=False,
        ),
    ]
