# Generated by Django 3.2.9 on 2021-11-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_auto_20211115_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='graph.region'),
        ),
    ]
