# Generated by Django 3.2.9 on 2021-11-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0009_alter_order_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buyerPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='fulfilmentShopId',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='params',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='subsidy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='vat',
            field=models.CharField(blank=True, choices=[('NO_VAT', 'NO_VAT'), ('VAT_0', 'VAT_0'), ('VAT_10', 'VAT_10'), ('VAT_10_110', 'VAT_10_110'), ('VAT_18', 'VAT_18'), ('VAT_18_118', 'VAT_18_118'), ('VAT_20', 'VAT_20'), ('VAT_20_120', 'VAT_20_120')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='warehouseId',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
