# Generated by Django 3.2.9 on 2021-11-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0010_auto_20211116_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_model', to='graph.order'),
            preserve_default=False,
        ),
    ]
