# Generated by Django 3.2.9 on 2021-11-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0012_auto_20211116_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('DELIVERY', 'DELIVERY'), ('PICKUP', 'PICKUP'), ('PROCESSING', 'PROCESSING'), ('PENDING', 'PENDING'), ('UNPAID', 'UNPAID')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='substatus',
            field=models.CharField(blank=True, choices=[('STARTED', 'STARTED'), ('ANTIFRAUD', 'ANTIFRAUD'), ('DELIVERY_SERVICE_UNDELIVERED', 'DELIVERY_SERVICE_UNDELIVERED'), ('PENDING_EXPIRED', 'PENDING_EXPIRED'), ('PROCESSING_EXPIRED', 'PROCESSING_EXPIRED'), ('REPLACING_ORDER', 'REPLACING_ORDER'), ('RESERVATION_EXPIRED', 'RESERVATION_EXPIRED'), ('RESERVATION_FAILED', 'RESERVATION_FAILED'), ('SHOP_FAILED', 'SHOP_FAILED'), ('SHOP_PENDING_CANCELLED', 'SHOP_PENDING_CANCELLED'), ('WAREHOUSE_FAILED_TO_SHIP', 'WAREHOUSE_FAILED_TO_SHIP'), ('USER_CHANGED_MIND', 'USER_CHANGED_MIND'), ('USER_NOT_PAID', 'USER_NOT_PAID'), ('USER_REFUSED_DELIVERY', 'USER_REFUSED_DELIVERY'), ('USER_REFUSED_PRODUCT', 'USER_REFUSED_PRODUCT'), ('USER_REFUSED_QUALITY', 'USER_REFUSED_QUALITY'), ('USER_UNREACHABLE', 'USER_UNREACHABLE'), ('PICKUP_SERVICE_RECEIVED', 'PICKUP_SERVICE_RECEIVED'), ('PICKUP_USER_RECEIVED', 'PICKUP_USER_RECEIVED')], default=None, max_length=50, null=True),
        ),
    ]
